#!/bin/bash

if [ -f /etc/grub.d/30_os-prober ]; then
  sed -i -e 's/    linux)/    linux_disable)/' /etc/grub.d/30_os-prober
else
  echo "No existe /etc/grub.d/30_os-prober"
fi

# Tipo de tabla de particiones (msdos o gpt)
part_table_type=$(parted /dev/sda print | grep -i 'partition table:' | sed -r  "s/^.* (.*)$/\1/")

# UUID *constante* de la particion de recuperacion
recovery_part_uuid="4a5d9a51-a26c-4d36-a500-bc3e6372cfb8"

# Numero de particion dentro del dispositivo para la particion de recuperacion
recovery_disk="/dev/disk/by-uuid/$recovery_part_uuid"
part_number=$( [ -h $recovery_disk ] && readlink $recovery_disk | sed -r "s/^.*sda(.*)$/\1/")

if [ -z "$part_number" ]; then
    echo "No se encontro la particion de recuperación standard."
    exit
fi    

if [ "$part_table_type" = msdos ]; then
    hard_disk_drive="hd0"
elif [ "$part_table_type" = gpt ]; then
    hard_disk_drive="/dev/sda"
fi        

drive_and_type_and_part_number="($hard_disk_drive,$part_table_type$part_number)"

LINUXPROBED=$( linux-boot-prober /dev/sda${part_number} 2> /dev/null | sort | uniq | tr ' ' '^' | paste -s -d ' ' )
LKERNEL="`echo ${LINUXPROBED} | cut -d ':' -f 4`"
LINITRD="`echo ${LINUXPROBED} | cut -d ':' -f 5`"
LPARAMS="`echo ${LINUXPROBED} | cut -d ':' -f 6- | tr '^' ' '`"

echo "
#!/bin/sh
exec tail -n +3 \$0
### BEGIN Recuperacion ###
   menuentry \"Sistema de recuperación\" --class gnu-linux --class gnu --class os {
     insmod part_$part_table_type
     insmod ext2
     set root='$drive_and_type_and_part_number'
     search --no-floppy --fs-uuid --set=root $recovery_part_uuid
     linux $LKERNEL $LPARAMS
     initrd $LINITRD
   }
### END Recuperacion ###" > /etc/grub.d/40_conig-recovery

echo "Agregada la partición de recuperación al grub"
chmod +x /etc/grub.d/40_conig-recovery

update-grub
